terraform destroy -auto-approve \
  -var="openshift_server=${{ secrets.OPENSHIFT_SERVER }}" \
  -var="openshift_token=${{ secrets.OPENSHIFT_TOKEN }}" \
  -var="db_password=${{ secrets.DB_PASSWORD }}" \
  -var="openshift_namespace=${{ secrets.OPENSHIFT_NAMESPACE }}" \
  -var="sandbox_ip=${{ secrets.SANDBOX_IP }}"